name: Preprocessing Pipeline

on:
  push:
    paths:
      - 'heart_disease_raw.csv'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas numpy scikit-learn

      - name: Run preprocessing
        run: python preprocessing/automate_Vanesha.py

      - name: Commit preprocessed dataset
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add preprocessing/heart_disease_preprocessing.csv
          git diff --staged --quiet || git commit -m "Auto: update preprocessed dataset [skip ci]"
          git push 